name: "Bump Version"

on:
  push:
    branches:
      - "main"

jobs:
  bump-version:
    name: "Bump Version on main"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.2

      - name: "cat package.json"
        run: cat package.json

      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: "v"
          commit-message: "CI: bumps version to {{version}} [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "cat package.json"
        run: cat package.json

      - name: "Output Step"
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
